version: '3.8'

services:
  mosquitto_broker_app:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: host

  control_app:
    build: . # Specifies the directory containing the Dockerfile
    container_name: control
    devices:
      - "/dev/input/js0:/dev/input/js0" # Grants the container access to the PlayStation controller

    volumes:
      - "./:/app" # Mounts the current directory to /app in the container
    network_mode: host # Uses the host network stack for the container
    working_dir: /app # Sets the working directory to /app inside the container
    # set up mosquitto broker
    command: python3 control.py # Runs the manual_control.py scripti
